title: Vaishak.D.A # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 MS in Computer science at USC |Data Analytics | Data Visualization | SQL | Tableau | Excel |Data Science |Machine Learning   <br><br>
  <a href="http://www.linkedin.com/in/vaishak-d-av">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
